kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: updater
  labels:
      name: updater
      app: updater
      tier: api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: updater
        app: updater
        tier: api
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
      containers:
        - name: updater
          imagePullPolicy: Always
          image: gronnbeck/redis-api-updater:naive
          resources:
            requests:
              cpu: 1
              memory: 250Mi
          env:
          - name: API_URL
            value: http://redis-api.default.svc.cluster.local:8080
