---
kind: Service
apiVersion: v1
metadata:
  name: vegetaserver
spec:
  selector:
    name: vegetaserver
    app: vegetaserver
    tier: api
  ports:
    - name: api
      protocol: TCP
      port: 8081

---
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: vegetaserver
  labels:
      name: vegetaserver
      app: vegetaserver
      tier: api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: vegetaserver
        app: vegetaserver
        tier: api
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
      containers:
        - name: vegetaserver
          imagePullPolicy: Always
          image: gronnbeck/vegetaserver
          env:
          - name: TARGET_URL
            value: http://helloworldserver.default.svc.cluster.local:8080
          ports:
            - name: api
              containerPort: 8081
          readinessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 20
            timeoutSeconds: 2
