---
kind: Service
apiVersion: v1
metadata:
  name: redis-api
spec:
  selector:
    name: redis-api
    app: redis-api
    tier: api
  ports:
    - name: api
      protocol: TCP
      port: 8080

---
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: redis-api
  labels:
      name: redis-api
      app: redis-api
      tier: api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: redis-api
        app: redis-api
        tier: api
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
      containers:
        - name: redis-api
          imagePullPolicy: Always
          image: gronnbeck/redis-api:naive
          resources:
            limits:
              cpu: 2
              memory: 1024Mi
            requests:
              cpu: 1
              memory: 500Mi
          env:
          - name: REDIS_ADDR
            value: redismaster.default.svc.cluster.local:6379
          ports:
            - name: api
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 20
            timeoutSeconds: 2
