---
kind: Service
apiVersion: v1
metadata:
  name: redis-api
spec:
  selector:
    name: redis-api
    app: redis-api
    tier: api
  ports:
    - name: api
      protocol: TCP
      port: 8080

---
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: redis-api
  labels:
      name: redis-api
      app: redis-api
      tier: api
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: redis-api
        app: redis-api
        tier: api
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
      containers:
        - name: redis-api
          imagePullPolicy: Always
          image: gronnbeck/redis-api:smarter
          resources:
            limits:
              cpu: 2
              memory: 1024Mi
            requests:
              cpu: 1
              memory: 500Mi
          env:
          - name: REDIS_ADDR_READ
            value: 127.0.0.1:6379
          - name: REDIS_ADDR_WRITE
            value: 127.0.0.1:7007
          - name: REDIS_PASS_WRITE
            valueFrom:
              configMapKeyRef:
                name: redis-write
                key: pass
          ports:
            - name: api
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 20
            timeoutSeconds: 2
        - name: redis-sidekick
          imagePullPolicy: Always
          image: gronnbeck/redis-with-config
          resources:
            limits:
              cpu: 2
              memory: 400Mi
            requests:
              cpu: 200m
              memory: 100Mi
          volumeMounts:
            - name: redis-config
              mountPath: /usr/local/etc/redis
        - name: ssl-tunnel
          imagePullPolicy: Always
          image: gronnbeck/compose-ssl-tunnel
          volumeMounts:
            - name: ssl-tunnel-priv-key
              mountPath: /var/redis-ssl-tunnel
              readOnly: true
          env:
            - name: REDIS_SSL_TUNNEL_HOST
              valueFrom:
                secretKeyRef:
                  name: compose-ssl-tunnel
                  key: host
            - name: REDIS_SSL_TUNNEL_PORT
              valueFrom:
                secretKeyRef:
                  name: compose-ssl-tunnel
                  key: port
            - name: REDIS_SSL_TUNNEL_DST_IP
              valueFrom:
                secretKeyRef:
                  name: compose-ssl-tunnel
                  key: dst_ip
            - name: REDIS_SSL_TUNNEL_SRC_PORT
              valueFrom:
                secretKeyRef:
                  name: compose-ssl-tunnel
                  key: src_port
      volumes:
        - name: redis-config
          configMap:
            # Provide the name of the ConfigMap containing the files you want
            # to add to the container
            name: redis-sidekick
        - name: ssl-tunnel-priv-key
          secret:
            secretName: ssl-tunnel-priv-key
