---
kind: Service
apiVersion: v1
metadata:
  name: aggregator
spec:
  selector:
    name: aggregator
    app: aggregator
    tier: api
  ports:
    - name: api
      protocol: TCP
      port: 8082

---
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: aggregator
  labels:
      name: aggregator
      app: aggregator
      tier: api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: aggregator
        app: aggregator
        tier: api
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
      containers:
        - name: aggregator
          imagePullPolicy: Always
          image: gronnbeck/aggregator
          env:
          - name: RUNTIME
            value: K8S
          ports:
            - name: api
              containerPort: 8082
          readinessProbe:
            httpGet:
              path: /
              port: 8082
            initialDelaySeconds: 20
            timeoutSeconds: 2
